random_seed: 42
algorithm: pso
metrics: editdist
kind: struct
max_iter: 30
metrics_subset: [2, 3, 5, 10, 15, 20, 30]
device: cuda
n_repos: 150
i_repo_start: 150
n_runs: 2
temp: 10
num_particles: 30
run_id: struct-pso-editdist-small
